# This is a basic workflow to help you get started with Actions

name: Docker Testing Matrix for manual installation script

# Controls when the action will run.
on:
  schedule:
    # Run once a week, in this case on Sundays
    - cron: "0 0 * * 0"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Run all combos, don't skip on failures
      matrix:
        # Here we will use different system images to test steps of installing Mephisto.
        # For now, it is just Ubuntu.
        system-version: ["ubuntu:22.04", "ubuntu:24.04"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build docker image - ${{ matrix.system-version }}
        run: docker build -f ./docker/dockerfiles/Dockerfile.ubuntu-24.04 -t mephisto_manual --build-arg BASE_IMAGE=${{ matrix.system-version }} .

      - name: Print out version numbers
        run: docker run mephisto_manual bash -c 'python --version && node --version && npm --version'

      # Runs a set of commands using the runners shell
      - name: Check that Mephisto was installed correctly
        run: |
          docker run mephisto_manual

      # Test that all Mephisto React apps can be built
      - name: Run command that removes and rebuilds all Mephisto React apps
        run: |
          docker run mephisto_manual bash -c 'mephisto scripts tests rebuild_all_mephisto_react_apps'
